host: 0.0.0.0
url: https://techaccelerator.com

#SEO https://github.com/jekyll/jekyll-seo-tag
gems:
  - jekyll-seo-tag

description: We craft on-demand, hands-on lab environments to educate, engage and ultimately empower enterprise customers, direct sales teams and channel partners, so they can get from Demo to PoC to PO faster

twitter:
  username: techaccel

author:
  twitter: dhekimian

social:
  name: TechAccelerator
  links:
    - https://twitter.com/techaccel
    - https://linkedin.com/company/techaccelerator

sass:
  sass_dir: _scss


excerpt_separator: <!--more-->

kramdown:
  input: GFM

permalink: /blog/:title/

collections:
  introduction:
    title: Introduction
    output: true
    permalink: /docs/:name/
    order: 1
  usage:
    title: Usage
    output: true
    permalink: /docs/:name/
    order: 2
  builder:
    title: Builder
    output: true
    permalink: /docs/:name/
    order: 3
  administration:
    title: Administration
    output: true
    permalink: /docs/:name/
    order: 4

defaults:
  - scope:
      path: ""
    values:
      layout: base
  - scope:
      path: pricing
    values:
      layout: pricing
  - scope:
      relative_path: docs
    values:
      layout: docs
  - scope:
      path: jobs
    values:
      layout: jobs
  - scope:
      path: legal
    values:
      layout: legal
  - scope:
      type: posts
    values:
      layout: post
  - scope:
      path: team
    values:
      layout: team
